owner: ZicklePop
repo: status-nyan-lol

sites:
  - name: Mastodon
    url: https://nyan.lol
  - name: Elk
    url: https://elk.nyan.lol

assignees:
  - ZicklePop

workflowSchedule:
  uptime: "*/15 * * * *"

status-website:
  cname: status.nyan.lol
  logoUrl: https://files.nyan.lol/site_uploads/files/000/000/002/@2x/83f8682fba7737b8.png
  name: nyan.lol
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
